### ISSUE TITLE
[Bug]: Panic handler swallows strack trace even in development mode

### ISSUE THREAD

**Issue by ringerc** [cloudnative-pg/cnpg-i-machinery#33]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### What happened?

If a CNPG-I plugin panics in a gRPC call handler, the plugin helper's registered panic handler intercepts the panic and logs it - without the stack trace.

Because the handler doesn't propagate the logger context (see https://github.com/cloudnative-pg/cnpg-i-machinery/pull/31) a custom logger configuration cannot be used to work around this either.

### Relevant log output

```shell
{"level":"info","ts":1719969643.970347,"caller":"pluginhelper/server.go:195","msg":"Panic occurred","error":"runtime error: invalid memory address or nil pointer dereference"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by armru** [comment]
Hello @ringerc, is this still relevant? Any proposed solutions?

**Comment by ringerc** [comment]
Yes, it's still relevant.

I wasn't able to quickly figure out what is going wrong here. Even after I fixed the various logging issues in https://github.com/cloudnative-pg/cnpg-i-machinery/pull/31, https://github.com/cloudnative-pg/cnpg-i-machinery/pull/12 and https://github.com/cloudnative-pg/cnpg-i-hello-world/pull/7 I didn't manage to get the zap logger to emit a stack trace from the panic handler.

**Comment by armru** [comment]
this is being tricky to solve haven't come up with a good solution so far
